spring:
  profiles:
    active: local

app:
  jwt:
    jwt-secret-key: wafflestudio
    jwt-expiration-in-ms: 10800000

cloud:
  aws:
    s3:
      bucket: waffle-team6
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true


---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/carrot?serverTimezone=UTC
    username: waffle-team6-server
    password: wafflestudio
    sql:
      init:
        mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      file-size-threshold: 3MB
      location: /tmp
      max-file-size: 100MB
      max-request-size: 100MB

  jackson:
    property-naming-strategy: SNAKE_CASE


---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://waffle-team6-carrot.cramsypnh1ch.ap-northeast-2.rds.amazonaws.com:3306/carrot?serverTimezone=UTC
    username: waffle-team6-server
    password: wafflestudio
    sql:
      init:
        mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      file-size-threshold: 100MB
      location: /home/ec2-user/images
      max-file-size: 100MB
      max-request-size: 100MB

  jackson:
    property-naming-strategy: SNAKE_CASE