spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/carrot?serverTimezone=UTC
    username: waffle-team6-server
    password: wafflestudio
    sql:
      init:
        mode: always
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://waffle-team6-carrot.cramsypnh1ch.ap-northeast-2.rds.amazonaws.com:3306/carrot?serverTimezone=UTC
    username: waffle-team6-server
    password: wafflestudio
    sql:
      init:
        mode: always
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: update
