spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            client_id: "a7789ca5f4326da2006d8fe1775e271a"
            client_secret: "ixipIBP8UZmbxNEDQHHoxqEH4tDjAybG"
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  datasource:
    url: jdbc:mysql://localhost:3306/carrot?serverTimezone=UTC
    username: waffle-team6-server
    password: wafflestudio
    sql:
      init:
        mode: always
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create

  servlet:
    multipart:
      file-size-threshold: 3MB
      location: /tmp
      max-file-size: 100MB
      max-request-size: 100MB


jwt:
  header: Authorization
  jwt-secret-key: wafflestudio
  jwt-expiration-in-ms: 10800000

kakao:
  url:
    auth: https://kauth.kakao.com/
    api: https://kapi.kakao.com/
---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://waffle-team6-carrot.cramsypnh1ch.ap-northeast-2.rds.amazonaws.com:3306/carrot?serverTimezone=UTC
    username: waffle-team6-server
    password: wafflestudio
    sql:
      init:
        mode: always
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: update

  servlet:
    multipart:
      file-size-threshold: 3MB
      location: /home/ec2-user/images
      max-file-size: 100MB
      max-request-size: 100MB